/**
 * Resolving URL params that accept either a row's `short_id` (the current
 * shareable form) or its UUID (links shared before short_ids existed).
 *
 * The convention across the app — saved_decks, lists, and matches all carry
 * an 8-char `short_id` generated by the same nanoid-style Postgres function —
 * is to pick the column by shape rather than probing both: a UUID-shaped
 * value can only be an `id`, anything else can only be a `short_id`. That
 * keeps the common path to a single round-trip while legacy links keep
 * resolving forever.
 */

const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}

/** Which column a URL param should be matched against. */
export function idColumn(value: string): "id" | "short_id" {
  return isUuid(value) ? "id" : "short_id";
}
