// Learned opponent-reply model — the policy ranker plugged into the
// planner's ReplyChooser seam.
//
// WHY: A3 (2026-07-21) showed selective deepening doesn't pay even with the
// nonlinear evaluator, which localizes the remaining search error in the
// hand-written opponent-reply rule ("hardest hit wins"): maxing over
// futures generated by a wrong reply predictor systematically prefers lines
// the predictor mispredicts. The ranker — trained by imitating the
// CHAMPION planner's actual choices — is a learned replacement: it knows,
// for instance, that a 0-damage condition attack or an energy-preserving
// stay-in can beat the hardest hit.
//
// The view it scores is the opponent's information set of the GHOST state:
// their hand is unrevealed placeholders, so hand-composition features read
// as zero and the decision leans on board/action features — exactly the
// public information a real player would predict a reply from.

import type { PlayerView } from "@/lib/engine/sim/view";
import type { SimMove } from "@/lib/engine/sim/moves";
import type { ReplyChooser } from "@/lib/engine/sim/planner";
import path from "node:path";
import {
  readPolicyArtifact,
  readPolicyArtifactFile,
  scoreCandidates,
  type PolicyRankerArtifact,
} from "./policyModel";
import { encodeActionFeatures, encodeStateFeatures } from "./features/policy";

/**
 * Build a ReplyChooser from a policy-ranker artifact. Resolution: explicit
 * path if given (evaluation harnesses measuring a candidate pre-promotion),
 * else the registry (`models.policy`, iff enabled). Returns null when no
 * usable artifact exists — the planner then keeps its built-in rule.
 */
export function createReplyChooser(explicitPath?: string): ReplyChooser | null {
  const artifact: PolicyRankerArtifact | null = explicitPath
    ? readPolicyArtifactFile(
        path.isAbsolute(explicitPath) ? explicitPath : path.join(process.cwd(), explicitPath),
      )
    : readPolicyArtifact();
  if (!artifact) return null;

  return (view: PlayerView, options: SimMove[]): SimMove | null => {
    if (options.length === 0) return null;
    if (options.length === 1) return options[0];
    const state = encodeStateFeatures(view);
    const { scores } = scoreCandidates(
      artifact,
      state,
      options.map((move) => encodeActionFeatures(view, move)),
    );
    let best = 0;
    for (let i = 1; i < scores.length; i++) {
      if (scores[i] > scores[best]) best = i;
    }
    return options[best];
  };
}
