-- Rewrite legacy collection variants as canonical variant keys.
-- Generated by dexter-ops/scripts/migrate_collection_variants.py.
--
-- Applied manually via the Supabase MCP `apply_migration` (see
-- tcgdexter-web/CLAUDE.md — there is no CI migration runner). Applied
-- 2026-08-10; apply_migration supplies its own transaction, so the BEGIN/COMMIT
-- this file was generated with are stripped below.
--
-- Reversible from public.user_card_collection_backup_20260810, taken
-- immediately before (2419 rows / 4413 qty, matching the post-migration
-- totals). Drop that table once the new keys have had a few days in the UI.
--
-- Rows are merged rather than replaced where two legacy strings collapse onto
-- the same canonical key, so the (user_id, set_id, number, variant) primary key
-- still holds and no quantity is lost.


-- `set_id`/`number` of '*' means the mapping holds for every card; specific
-- values mean it was resolved against that card's actual printings.
CREATE TEMP TABLE variant_remap (
  set_id      text NOT NULL,
  number      text NOT NULL,
  old_variant text NOT NULL,
  new_variant text NOT NULL
) ON COMMIT DROP;

INSERT INTO variant_remap (set_id, number, old_variant, new_variant) VALUES
  ('*', '*', 'Cosmos Holo', 'holo:f=cosmos'),
  ('*', '*', 'Holo', 'holo'),
  ('*', '*', 'Metal Card', 'metal'),
  ('*', '*', 'Non-holo', 'normal'),
  ('*', '*', 'Normal', 'normal'),
  ('*', '*', 'Normal (Misaligned Energy Text)', 'normal:s=shifted-energy-cost'),
  ('*', '*', 'Normal (Shadowless)', 'normal:s=shadowless'),
  ('*', '*', 'Normal Holo', 'holo'),
  ('*', '*', 'Play! Pokémon Prize Pack, Non-holo', 'normal:t=player-rewards-program'),
  ('*', '*', 'Poké Ball Reverse Holo', 'reverse:f=pokeball'),
  ('*', '*', 'Reverse Holo', 'reverse'),
  ('*', '*', 'Tinsel Holo', 'holo:f=tinsel'),
  ('*', '*', 'cosmos_holo', 'holo:f=cosmos'),
  ('*', '*', 'duskball_reverse_holo', 'reverse:f=duskball'),
  ('*', '*', 'energy_reverse_holo', 'reverse:f=energy'),
  ('*', '*', 'metal_card', 'metal'),
  ('*', '*', 'misaligned_energy', 'normal:s=shifted-energy-cost'),
  ('*', '*', 'non_holo', 'normal'),
  ('*', '*', 'pokeball_reverse_holo', 'reverse:f=pokeball'),
  ('*', '*', 'prize_pack_non_holo', 'normal:t=player-rewards-program'),
  ('*', '*', 'reverse_holo', 'reverse'),
  ('*', '*', 'shadowless', 'normal:s=shadowless'),
  ('*', '*', 'tinsel_holo', 'holo:f=tinsel'),
  ('base2', '45', 'first_edition', 'normal:t=1st-edition'),
  ('base2', '50', 'first_edition', 'normal:t=1st-edition'),
  ('base3', '35', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '47', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '49', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '50', 'first_edition', 'normal:t=1st-edition'),
  ('base3', '53', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '54', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '56', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '58', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('base3', '62', 'first_edition', 'normal:f=galaxy:t=1st-edition'),
  ('basep', '3', 'first_movie', 'normal:t=1st-movie'),
  ('sv2', '46', 'holiday_calendar_2025', 'normal:t=snowflake'),
  ('sv4', '190', 'holiday_calendar_2025', 'holo:t=snowflake'),
  ('sv7', '149', 'holiday_calendar_2025', 'holo:t=snowflake'),
  ('sv8', '47', 'holiday_calendar_2025', 'normal:t=snowflake'),
  ('sv8pt5', '26', 'holiday_calendar_2025', 'holo:t=snowflake'),
  ('sv9', '32', 'holiday_calendar_2025', 'holo:t=snowflake'),
  ('sv3pt5', '9', 'jumbo', 'holo:z=jumbo'),
  ('svp', '196', 'jumbo', 'lenticular:z=jumbo'),
  ('svp', '205', 'jumbo', 'holo:z=jumbo'),
  ('svp', '208', 'jumbo', 'holo:z=jumbo'),
  ('me1', '77', 'prize_pack', 'holo:t=player-rewards-program'),
  ('me1', '94', 'prize_pack', 'holo:t=player-rewards-program'),
  ('sv9', '79', 'prize_pack', 'holo:t=player-rewards-program'),
  ('basep', '18', 'promo', 'holo'),
  ('svp', '124', 'promo', 'holo'),
  ('swshp', 'SWSH196', 'promo', 'normal'),
  ('swshp', 'SWSH201', 'promo', 'normal'),
  ('swshp', 'SWSH229', 'promo', 'normal'),
  ('swshp', 'SWSH291', 'promo', 'normal'),
  ('sv6', '40', 'tm_stamp_jumbo', 'holo:t=set-logo:z=jumbo');

-- Per-card rows win over wildcards, so a card-specific resolution isn't
-- overridden by a generic one for the same legacy string.
CREATE TEMP VIEW remap_for_row AS
SELECT DISTINCT ON (c.user_id, c.set_id, c.number, c.variant)
       c.user_id, c.set_id, c.number, c.variant AS old_variant, r.new_variant
FROM public.user_card_collection c
JOIN variant_remap r
  ON r.old_variant = c.variant
 AND (r.set_id = '*' OR (r.set_id = c.set_id AND r.number = c.number))
ORDER BY c.user_id, c.set_id, c.number, c.variant, (r.set_id = '*');

-- 1. Fold rows whose target key already exists for that user into it.
WITH folded AS (
  DELETE FROM public.user_card_collection c
  USING remap_for_row r
  WHERE c.user_id = r.user_id AND c.set_id = r.set_id
    AND c.number = r.number AND c.variant = r.old_variant
    AND EXISTS (
      SELECT 1 FROM public.user_card_collection t
      WHERE t.user_id = c.user_id AND t.set_id = c.set_id
        AND t.number = c.number AND t.variant = r.new_variant
    )
  RETURNING c.user_id, c.set_id, c.number, r.new_variant, c.quantity
)
UPDATE public.user_card_collection t
SET quantity = t.quantity + f.quantity
FROM folded f
WHERE t.user_id = f.user_id AND t.set_id = f.set_id
  AND t.number = f.number AND t.variant = f.new_variant;

-- 2. Rename the rest in place.
UPDATE public.user_card_collection c
SET variant = r.new_variant
FROM remap_for_row r
WHERE c.user_id = r.user_id AND c.set_id = r.set_id
  AND c.number = r.number AND c.variant = r.old_variant;
